/*  =========================================================================
    filemq Node.js binding header file

    Copyright (c) the Contributors as noted in the AUTHORS file.
    This file is part of FileMQ, a C implemenation of the protocol:
    https://github.com/danriegsecker/filemq2.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef FILEMQ_BINDING_H_INCLUDED
#define FILEMQ_BINDING_H_INCLUDED

#define FILEMQ_BUILD_DRAFT_API

#include "../../../czmq/bindings/nodejs/binding.h"
#include "filemq.h"
#include "nan.h"

using namespace v8;
using namespace Nan;

#endif
