/*  =========================================================================
    filemq - generated layer of public API

    Copyright (c) the Contributors as noted in the AUTHORS file.
    This file is part of FileMQ, a C implemenation of the protocol:
    https://github.com/danriegsecker/filemq2.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef FILEMQ_LIBRARY_H_INCLUDED
#define FILEMQ_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>

//  FILEMQ version macros for compile-time API detection
#define FILEMQ_VERSION_MAJOR 2
#define FILEMQ_VERSION_MINOR 0
#define FILEMQ_VERSION_PATCH 0

#define FILEMQ_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define FILEMQ_VERSION \
    FILEMQ_MAKE_VERSION(FILEMQ_VERSION_MAJOR, FILEMQ_VERSION_MINOR, FILEMQ_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined FILEMQ_STATIC
#       define FILEMQ_EXPORT
#   elif defined FILEMQ_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define FILEMQ_EXPORT __declspec(dllexport)
#       else
#           define FILEMQ_EXPORT
#       endif
#   elif defined FILEMQ_EXPORTS
#       define FILEMQ_EXPORT __declspec(dllexport)
#   else
#       define FILEMQ_EXPORT __declspec(dllimport)
#   endif
#   define FILEMQ_PRIVATE
#elif defined (__CYGWIN__)
#   define FILEMQ_EXPORT
#   define FILEMQ_PRIVATE
#else
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define FILEMQ_PRIVATE __attribute__ ((visibility ("hidden")))
#       define FILEMQ_EXPORT __attribute__ ((visibility ("default")))
#   else
#       define FILEMQ_PRIVATE
#       define FILEMQ_EXPORT
#   endif
#endif

//  Project has no stable classes, so we build the draft API
#undef  FILEMQ_BUILD_DRAFT_API
#define FILEMQ_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef FILEMQ_BUILD_DRAFT_API
typedef struct _fmq_msg_t fmq_msg_t;
#define FMQ_MSG_T_DEFINED
typedef struct _fmq_server_t fmq_server_t;
#define FMQ_SERVER_T_DEFINED
typedef struct _fmq_client_t fmq_client_t;
#define FMQ_CLIENT_T_DEFINED
#endif // FILEMQ_BUILD_DRAFT_API


//  Public classes, each with its own header file
#ifdef FILEMQ_BUILD_DRAFT_API
#include "fmq_msg.h"
#include "fmq_server.h"
#include "fmq_client.h"
#endif // FILEMQ_BUILD_DRAFT_API

#ifdef FILEMQ_BUILD_DRAFT_API

#ifdef __cplusplus
extern "C" {
#endif

//  Self test for private classes
FILEMQ_EXPORT void
    filemq_private_selftest (bool verbose, const char *subtest);

#ifdef __cplusplus
}
#endif
#endif // FILEMQ_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
